-- Migration: soft delete + audit trail (created_by/updated_by/deleted_by/deleted_at)
-- untuk users, categories, assets, packages, loans, repairs.
-- Jalankan file ini jika database sudah ada dan tidak ingin di-reset ulang (schema.sql akan DROP semua tabel).
-- Aman dijalankan berkali-kali (idempotent) di MariaDB 10.11 / MySQL 8 yang mendukung
-- `ADD COLUMN IF NOT EXISTS`. Jika versi server tidak mendukungnya, hapus klausa
-- "IF NOT EXISTS" dan jalankan manual setelah memeriksa kolom belum ada.

USE bmn_streaming;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS created_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS created_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE assets
    ADD COLUMN IF NOT EXISTS created_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

ALTER TABLE packages
    ADD COLUMN IF NOT EXISTS created_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE loans
    ADD COLUMN IF NOT EXISTS created_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

ALTER TABLE repairs
    ADD COLUMN IF NOT EXISTS created_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
